// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
const go = {
  "main": {
    "App": {
      /**
       * GetMachineId
       * @returns {Promise<string|Error>}  - Go Type: string
       */
      "GetMachineId": () => {
        return window.go.main.App.GetMachineId();
      },
      /**
       * ReadUserConfig
       * @param {string} arg1 - Go Type: string
       * @returns {Promise<string|Error>}  - Go Type: string
       */
      "ReadUserConfig": (arg1) => {
        return window.go.main.App.ReadUserConfig(arg1);
      },
      /**
       * WriteUserConfig
       * @param {string} arg1 - Go Type: string
       * @param {string} arg2 - Go Type: string
       * @returns {Promise<number|Error>}  - Go Type: interface {}
       */
      "WriteUserConfig": (arg1, arg2) => {
        return window.go.main.App.WriteUserConfig(arg1, arg2);
      },
    },
  },

};
export default go;
